name: ucsc_blat
owner: yating-l
description: Standalone blat sequence search command line tool
homepage_url: http://genome.ucsc.edu/goldenPath/help/blatSpec.html
type: unrestricted
categories: 
- Sequence Analysis
exclude:
  - tool_test_output.html
  - tool_test_output.json
